{{- range .Values.Deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  replicas: {{ .replicaCount }}
  strategy:
    {{- toYaml .strategy | nindent 4 }}
  template:
    metadata:
      labels:
        app: {{ .name }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      containers:
        {{- range .containers }}
        - name: {{ .name }}
          image: {{ .image }}
          {{- if .commands }}
          command:
            {{- range .commands }}
              - {{ . }}
            {{- end }}
          {{- end }}
          {{- if .args }}
          args:
            {{- range .args }}
              - {{ . }}
            {{- end }}
          {{- end }}
          {{- if .ports }}  
          ports:
            {{- range .ports }}
            - containerPort: {{ .containerPort }}
            {{- end }}
          {{- end }}
          {{- if .env }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          {{- if .livenessProbe }}
          livenessProbe:
            exec:
              command:
                {{- range .livenessProbe.exec.command }}
                - {{ . | quote }}
                {{- end }}
            failureThreshold: {{ .livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .livenessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .volumeMounts }}
          volumeMounts:
            {{- range .volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          {{- end }}
        {{- end }}
      restartPolicy: {{ .restartPolicy }}
      {{- if .volumes }}
      volumes:
        {{- range .volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .persistentVolumeClaim.claimName }}
        {{- end }}
      {{- end }}
---
{{- end }}