{{- if .Values.redis.create -}}
{{-  $fullName := printf "%s-%s" .Release.Name .Values.redis.persistentVolumeClaim.name -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $fullName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
{{- end }}
