{{- if .Values.redis.create -}}
{{-  $fullName := printf "%s-%s" .Release.Name .Values.redis.name -}}
{{-  $volumeFullName := printf "%s-%s" .Release.Name .Values.redis.persistentVolumeClaim.name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $fullName }}
spec:
  selector:
    matchLabels:
      app: {{ $fullName }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ $fullName }}
    spec:
      containers:
        - name: redis
          image: {{ $.Values.redis.image }}
          env:
            - name: REDIS_DISABLE_COMMANDS
              value: FLUSHDB,FLUSHALL
            - name: REDIS_PASSWORD
              value: {{ $.Values.redis.password }}
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
          volumeMounts:
            - name: {{ $volumeFullName }}
              mountPath: /bitnami/redis/data
      restartPolicy: Always
      volumes:
        - name: {{ $volumeFullName }}
          persistentVolumeClaim:
            claimName: {{ $volumeFullName }}
{{- end }}    
