apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/hive: "true"
        io.kompose.service: redis
    spec:
      containers:
        - env:
            - name: REDIS_DISABLE_COMMANDS
              value: FLUSHDB,FLUSHALL
            - name: REDIS_PASSWORD
              value: ca871bee997a80289fcaddd948717365
          image: bitnami/redis:7.0.8
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
          name: redis
          resources: {}
          volumeMounts:
            - mountPath: /bitnami/redis/data
              name: redis-claim0
      restartPolicy: Always
      volumes:
        - name: redis-claim0
          persistentVolumeClaim:
            claimName: redis-claim0
