apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
  replicas: {{ $.Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}
    spec:
      containers:
        - name: {{ $.Release.Name }}
          image: {{ $.Values.image.repository }}
          command: {{ $.Values.image.command }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          resources:
            limits:
              memory: {{ $.Values.resources.limits.memory }}
              cpu: {{ $.Values.resources.limits.cpu }}
            requests:
              memory: {{ $.Values.resources.requests.memory }}
              cpu: {{ $.Values.resources.requests.cpu }}